In [1]:
import pandas as pd

In [2]:
pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',sep='\t')

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [11]:
df=pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',sep='\t')

In [12]:
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [13]:
df.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [14]:
#Create New Column
dollar=lambda x:float(x[1:-1])
df['item_price_Dollars']=df['item_price'].apply(dollar)

In [15]:
df.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price             object
item_price_Dollars    float64
dtype: object

In [18]:
#Add new Column Item Price in Ruppees
df['item_price_ruppes']=df['item_price_Dollars']*72

In [19]:
df

,order_id,quantity,item_name,choice_description,item_price,item_price_Dollars,item_price_ruppes
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39,172.08
1,1,1,Izze,[Clementine],$3.39,3.39,244.08
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39,244.08
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39,172.08
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98,1222.56
...,...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75,846.00
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75,846.00
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25,810.00
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75,630.00
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75,630.00

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
 5   item_price_Dollars  4622 non-null   float64
 6   item_price_ruppes   4622 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 252.9+ KB

In [26]:
df.groupby('item_name').sum()

,order_id,quantity,item_price_Dollars,item_price_ruppes
item_name,,,,
6 Pack Soft Drink,52322,55,356.95,25700.40
Barbacoa Bowl,53972,66,672.36,48409.92
Barbacoa Burrito,74718,91,894.75,64422.00
Barbacoa Crispy Tacos,5613,12,120.21,8655.12
Barbacoa Salad Bowl,9708,10,106.40,7660.80
Barbacoa Soft Tacos,18725,25,250.46,18033.12
Bottled Water,175944,211,302.56,21784.32
Bowl,472,4,29.60,2131.20
Burrito,1550,6,44.40,3196.80
Canned Soda,76396,126,137.34,9888.48
Canned Soft Drink,304753,351,438.75,31590.00
Carnitas Bowl,62742,71,736.71,53043.12
Carnitas Burrito,51652,60,597.83,43043.76
Carnitas Crispy Tacos,5868,8,77.96,5613.12
Carnitas Salad,1500,1,8.99,647.28
Carnitas Salad Bowl,6693,6,66.34,4776.48
Carnitas Soft Tacos,37673,40,375.94,27067.68
Chicken Bowl,713926,761,7342.73,528676.56
Chicken Burrito,497303,591,5575.82,401459.04
Chicken Crispy Tacos,47382,50,472.13,33993.36
Chicken Salad,10465,9,81.09,5838.48
Chicken Salad Bowl,117104,123,1228.75,88470.00
Chicken Soft Tacos,98395,120,1108.09,79782.48
Chips,208004,230,494.34,35592.48
Chips and Fresh Tomato Salsa,100419,130,361.36,26017.92
Chips and Guacamole,449959,506,2201.04,158474.88
Chips and Mild Fresh Tomato Salsa,279,1,3.00,216.00
Chips and Roasted Chili Corn Salsa,14999,23,67.85,4885.20
Chips and Roasted Chili-Corn Salsa,17462,18,43.02,3097.44
Chips and Tomatillo Green Chili Salsa,41170,45,132.75,9558.00
Chips and Tomatillo Red Chili Salsa,45556,50,147.50,10620.00
Chips and Tomatillo-Green Chili Salsa,21826,33,78.87,5678.64
Chips and Tomatillo-Red Chili Salsa,18344,25,59.75,4302.00
Crispy Tacos,434,2,14.80,1065.60
Izze,10587,20,67.80,4881.60
Nantucket Nectar,21814,29,98.31,7078.32
Salad,1150,2,14.80,1065.60
Side of Chips,84769,110,185.90,13384.80
Steak Bowl,193752,221,2260.19,162733.68
Steak Burrito,328437,386,3851.43,277302.96
Steak Crispy Tacos,35818,36,357.34,25728.48
Steak Salad,2362,4,35.66,2567.52
Steak Salad Bowl,29590,31,343.59,24738.48
Steak Soft Tacos,50177,56,536.05,38595.60
Veggie Bowl,72270,87,867.99,62495.28
Veggie Burrito,80962,97,934.77,67303.44
Veggie Crispy Tacos,668,1,8.49,611.28
Veggie Salad,7265,6,50.94,3667.68
Veggie Salad Bowl,17303,18,182.50,13140.00
Veggie Soft Tacos,5520,8,73.96,5325.12

In [24]:
c=c.sum()

In [25]:
c.sort_values(['quantity'],ascending=False)

,order_id,quantity,item_price_Dollars,item_price_ruppes
item_name,,,,
Chicken Bowl,713926,761,7342.73,528676.56
Chicken Burrito,497303,591,5575.82,401459.04
Chips and Guacamole,449959,506,2201.04,158474.88
Steak Burrito,328437,386,3851.43,277302.96
Canned Soft Drink,304753,351,438.75,31590.00
Chips,208004,230,494.34,35592.48
Steak Bowl,193752,221,2260.19,162733.68
Bottled Water,175944,211,302.56,21784.32
Chips and Fresh Tomato Salsa,100419,130,361.36,26017.92
Canned Soda,76396,126,137.34,9888.48
Chicken Salad Bowl,117104,123,1228.75,88470.00
Chicken Soft Tacos,98395,120,1108.09,79782.48
Side of Chips,84769,110,185.90,13384.80
Veggie Burrito,80962,97,934.77,67303.44
Barbacoa Burrito,74718,91,894.75,64422.00
Veggie Bowl,72270,87,867.99,62495.28
Carnitas Bowl,62742,71,736.71,53043.12
Barbacoa Bowl,53972,66,672.36,48409.92
Carnitas Burrito,51652,60,597.83,43043.76
Steak Soft Tacos,50177,56,536.05,38595.60
6 Pack Soft Drink,52322,55,356.95,25700.40
Chips and Tomatillo Red Chili Salsa,45556,50,147.50,10620.00
Chicken Crispy Tacos,47382,50,472.13,33993.36
Chips and Tomatillo Green Chili Salsa,41170,45,132.75,9558.00
Carnitas Soft Tacos,37673,40,375.94,27067.68
Steak Crispy Tacos,35818,36,357.34,25728.48
Chips and Tomatillo-Green Chili Salsa,21826,33,78.87,5678.64
Steak Salad Bowl,29590,31,343.59,24738.48
Nantucket Nectar,21814,29,98.31,7078.32
Chips and Tomatillo-Red Chili Salsa,18344,25,59.75,4302.00
Barbacoa Soft Tacos,18725,25,250.46,18033.12
Chips and Roasted Chili Corn Salsa,14999,23,67.85,4885.20
Izze,10587,20,67.80,4881.60
Veggie Salad Bowl,17303,18,182.50,13140.00
Chips and Roasted Chili-Corn Salsa,17462,18,43.02,3097.44
Barbacoa Crispy Tacos,5613,12,120.21,8655.12
Barbacoa Salad Bowl,9708,10,106.40,7660.80
Chicken Salad,10465,9,81.09,5838.48
Carnitas Crispy Tacos,5868,8,77.96,5613.12
Veggie Soft Tacos,5520,8,73.96,5325.12
Burrito,1550,6,44.40,3196.80
Veggie Salad,7265,6,50.94,3667.68
Carnitas Salad Bowl,6693,6,66.34,4776.48
Bowl,472,4,29.60,2131.20
Steak Salad,2362,4,35.66,2567.52
Salad,1150,2,14.80,1065.60
Crispy Tacos,434,2,14.80,1065.60
Chips and Mild Fresh Tomato Salsa,279,1,3.00,216.00
Carnitas Salad,1500,1,8.99,647.28
Veggie Crispy Tacos,668,1,8.49,611.28